job:
  runModel:
    parameters:

    inputs:
      approved_loans: "inputs/accepted_loans_truncated.csv"

    outputs:
      loans_dq_metrics: "outputs/dq_outputs.csv"
      approved_loans_clean: "outputs/accepted_cleaned.csv"