job:
  runModel:
    parameters:
      testparam: 1
    inputs:
      approved_loans: "C:/Users/hwach/Documents/datasets/accepted_2007_to_2018Q4.csv"

    outputs:
      loans_dq_metrics: "C:/Users/hwach/Documents/tracproj/dq_outputs.csv"