job:
  runModel:
    parameters:
      eur_usd_rate: 1.2071
      default_weighting: 1.5
      filter_defaults: false

    inputs:
      customer_loans: "inputs/loans.csv"

    outputs:
      profit_by_region: "outputs/profit_by_region.csv"
      